import random
import numpy as np

class Figure:
    def __init__(self, filepath: str=None, grid_size: tuple=None):
        self.file_path = None
        self.comment = "Generated by Figure Generator"
        self.maxActions = 0
        self.maxJokers = 0
        self.maxJokerSize = 0
        self.grid = None

        if filepath is None:
            self._generate_random_grid(grid_size) # Generate random grid
        else:
            self._read_file(filepath) # Read grid from file

    def _read_file(self, file_path: str):
        import json
        with open(file_path, "r") as f:
            data = json.load(f)
        self.file_path = file_path
        self.comment = data.get("comment", self.comment)

        self.maxActions = data.get("maxActions", self.maxActions)
        self.maxJokers = data.get("maxJokers", self.maxJokers)
        self.maxJokerSize = data.get("maxJokerSize", self.maxJokerSize)
        self.grid = np.array(data["grid"])
    
    def _generate_random_grid(self, grid_size: tuple=None):
        grid_size = grid_size if grid_size is not None else (random.randrange(5, 501, 5), random.randrange(5, 501, 5))
        
        self.grid = np.random.randint(0, 8, size=grid_size)
        self.comment = f"Randomly generated grid of size {grid_size[0]}x{grid_size[1]}"
        self.maxActions = grid_size[0] * grid_size[1] // 2
        self.maxJokers = max(1, (grid_size[0] * grid_size[1]) // 50)
        self.maxJokerSize = max(5, (grid_size[0] * grid_size[1]) // 10)
    
    def random_action(self, joker: bool= False) -> str:
        grid_height, grid_width = self.grid.shape
        random_point_1 = (np.random.randint(0, grid_width), np.random.randint(0, grid_height))
        random_point_2 = (np.random.randint(random_point_1[0], grid_width), np.random.randint(random_point_1[1], grid_height))
        if joker:
            return "JOKER " + "{} {} {} {}".format(random_point_1[0], random_point_1[1], min(random_point_2[0], random_point_1[0] + self.maxJokerSize), min(random_point_2[1], random_point_1[1] + self.maxJokerSize))
        else:
            color = random.randint(0, 7)
            return "RECT " + "{} {} {} {} {}".format(random_point_1[0], random_point_1[1], random_point_2[0], random_point_2[1], color)


if __name__ == '__main__':
    # Read grid from file
    figure = Figure(filepath="../datasets/3_mchat.json")
    print("Grid from File Shape:", figure.grid.shape)
    grid = figure.grid
    print("Shape of Generated Grid:", grid.shape)
    print("Generated Grid:\n", grid)
    action = figure.random_action(joker=True)
    print("Generated Action:", action)

    # Generate random grid
    figure = Figure()
    print("Shape of Generated Grid:", figure.grid.shape)
    print("Generated Grid:\n", figure.grid)